services:
  accounts:
    image: "kishoreuputoori/accounts:s1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kishoreuputoori
  loans:
    image: "kishoreuputoori/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kishoreuputoori
  cards:
    image: "kishoreuputoori/cards:s3"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kishoreuputoori
networks:
  kishoreuputoori:
    driver: "bridge"